export const projectCategories = [
  { sortOrder: 1, slug: "shoring", nameAr: "سند حفريات", nameEn: "Shoring" },
  {
    sortOrder: 2,
    slug: "shotcrete",
    nameAr: "شوتكريت",
    nameEn: "Shotcrete",
  },
  {
    sortOrder: 3,
    slug: "dewatering",
    nameAr: "نزح مياه",
    nameEn: "Dewatering",
  },
  {
    sortOrder: 4,
    slug: "micropile",
    nameAr: "ميكروبايل",
    nameEn: "Micropile",
  },
  {
    sortOrder: 5,
    slug: "perforated-pipe",
    nameAr: "الأنابيب المثقبة",
    nameEn: "Perforated Pipe",
  },
] as const;

export const initialSettings = {
  key: "main" as const,
  phones: [
    { display: "+966 50 185 0513", raw: "+966501850513" },
    { display: "+966 55 460 1539", raw: "+966554601539" },
  ],
  whatsappNumber: "+966501850513",
  email: "info@asasalaamaq.com",
  website: "asasalaamaq.com",
  location: {
    ar: { city: "الرياض", country: "المملكة العربية السعودية" },
    en: { city: "Riyadh", country: "Saudi Arabia" },
  },
  social: {},
  stats: [
    {
      key: "years-experience",
      value: 10,
      suffixAr: "+",
      suffixEn: "+",
      labelAr: "سنة خبرة",
      labelEn: "Years of Experience",
      sortOrder: 1,
    },
    {
      key: "completed-projects",
      value: 20,
      suffixAr: "+",
      suffixEn: "+",
      labelAr: "مشروع منجز",
      labelEn: "Projects Completed",
      sortOrder: 2,
    },
    {
      key: "max-supported-depth",
      value: 18,
      suffixAr: "م",
      suffixEn: "m",
      labelAr: "أقصى عمق تم تدعيمه",
      labelEn: "Maximum Supported Depth",
      sortOrder: 3,
    },
    {
      key: "safety-commitment",
      value: 100,
      suffixAr: "%",
      suffixEn: "%",
      labelAr: "التزام بالسلامة",
      labelEn: "Safety Commitment",
      sortOrder: 4,
    },
  ],
};

export const legacyGallery = [
  {
    order: 1,
    file: "img (1).webp",
    slug: "legacy-gallery-01",
    category: "perforated-pipe",
    titleAr: "تمديد الأنابيب المثقبة للتصريف",
    titleEn: "Perforated pipe drainage installation",
  },
  {
    order: 2,
    file: "img (2).webp",
    slug: "legacy-gallery-02",
    category: "shoring",
    titleAr: "أعمال حفر وسند الجوانب",
    titleEn: "Drilling and shoring operations",
  },
  {
    order: 3,
    file: "img (3).webp",
    slug: "legacy-gallery-03",
    category: "shoring",
    titleAr: "سند حفريات عميقة",
    titleEn: "Deep excavation shoring",
  },
  {
    order: 4,
    file: "img (4).webp",
    slug: "legacy-gallery-04",
    category: "shoring",
    titleAr: "تركيب أنظمة التثبيت",
    titleEn: "Anchor stabilization installation",
  },
  {
    order: 5,
    file: "img (5).webp",
    slug: "legacy-gallery-05",
    category: "micropile",
    titleAr: "جدران الخوازيق المتلاصقة",
    titleEn: "Contiguous pile walls",
  },
  {
    order: 6,
    file: "img (6).webp",
    slug: "legacy-gallery-06",
    category: "dewatering",
    titleAr: "معدات ضخ ونزح المياه الجوفية",
    titleEn: "Groundwater dewatering equipment",
  },
  {
    order: 7,
    file: "img (7).webp",
    slug: "legacy-gallery-07",
    category: "shoring",
    titleAr: "تجهيز موقع العمل",
    titleEn: "Site preparation works",
  },
  {
    order: 8,
    file: "img (8).webp",
    slug: "legacy-gallery-08",
    category: "shoring",
    titleAr: "أنظمة الدعم المؤقت",
    titleEn: "Temporary support systems",
  },
  {
    order: 9,
    file: "img (9).webp",
    slug: "legacy-gallery-09",
    category: "shoring",
    titleAr: "تدعيم الجوانب والرقابة الميدانية",
    titleEn: "Side support and quality control",
  },
  {
    order: 10,
    file: "img (10).webp",
    slug: "legacy-gallery-10",
    category: "shoring",
    titleAr: "معدات الحفر الثقيلة",
    titleEn: "Heavy drilling equipment",
  },
  {
    order: 11,
    file: "img (12).webp",
    slug: "legacy-gallery-11",
    category: "shoring",
    titleAr: "أعمال التدعيم وسند الجوانب الخشبي",
    titleEn: "Shoring reinforcement and concrete",
  },
  {
    order: 12,
    file: "img (11).webp",
    slug: "legacy-gallery-12",
    category: "shoring",
    titleAr: "أعمال تسليح وتثبيت السند",
    titleEn: "Timber shoring and wall support",
  },
  {
    order: 13,
    file: "img (13).webp",
    slug: "legacy-gallery-13",
    category: "shotcrete",
    titleAr: "تنفيذ ميداني متقدم",
    titleEn: "Advanced field execution",
  },
  {
    order: 14,
    file: "img (14).webp",
    slug: "legacy-gallery-14",
    category: "shotcrete",
    titleAr: "أعمال رش الخرسانة (شوتكريت)",
    titleEn: "Shotcrete spraying operations",
  },
  {
    order: 15,
    file: "img (15).webp",
    slug: "legacy-gallery-15",
    category: "perforated-pipe",
    titleAr: "تركيب شبكات الأنابيب المثقبة بالموقع",
    titleEn: "On-site perforated pipe network installation",
  },
] as const;
